### ISSUE TITLE
cant play movies on C more

### ISSUE THREAD

**Issue by hexez6** [emilsvennesson/kodi-cmore#16]
Hi guys.

The Cmore addon cant play any movies it just gives an error saying it cant play the movie, I have installed bouth script.module.requests and Script.module.inputstreamhelper. I have uploaded the log file from kodi, hope you can help :).

[Kodi Log.txt](https://github.com/emilsvennesson/kodi-cmore/files/1714622/Kodi.Log.txt)

**Comment by emilsvennesson** [comment]
Hi!

It looks like you haven't enabled debug logging in the Kodi settings. Could you please post a new log with debug logging activated?

**Comment by hexez6** [comment]
Hi! 

Sure here it is with debug mode on, hope you can help :)

[log-2018-02-11-19.01.39.zip](https://github.com/emilsvennesson/kodi-cmore/files/1714726/log-2018-02-11-19.01.39.zip)

**Comment by emilsvennesson** [comment]
Thank you for the log file. 

The problem here is that there is no `libwidevinecdm.so` available for 64-bit ARM processors. What you can do is to switch to a LibreELEC build that runs with 32-bit userland libraries ([such as Raybuntu's builds)](https://forum.libreelec.tv/thread/4248-libreelec-krypton-leia-agile-build-for-odroid-c2-rock64-wetek-hub-wetek-play2/), otherwise you won't be able to play any DRM protected content.

**Comment by hexez6** [comment]
Hi.
I have just intalled the Raybuntus build as you was saying and it works perfect!! Thank you very much :)

**Comment by emilsvennesson** [comment]
Perfect! :-)
