### ISSUE TITLE
Login API has changed

### ISSUE THREAD

**Issue by macardi** [emilsvennesson/kodi-cmore#33]
Since yesterday I got an error from the plugin when trying to start a stream

[log](https://paste.ubuntu.com/p/RDDymfCVTY/)

**Comment by kjerstadius** [comment]
I'm seeing the same problem. If my digging so far is correct, the issue lies with the credentials request during login. Could it be that CMore updated their API and now require a slightly different request? I'm talking about this piece of code (in the function `login`):

```
credentials = self.make_request(url, method, params=params, payload=payload)
```
At present, instead of returning the expected JSON result it returns an html response and a 503 error. I'm trying to understand how this can be fixed, but I don't really have any experience with the APIs of these streaming services.

**Comment by kjerstadius** [comment]
I wonder if the problem is that legacy accounts aren't allowed anymore. The current app configuration that gets downloaded from the CMore servers contain this field:
```
"useLegacyAccount": false,
```
I wonder if the problem is that a legacy account is exactly what this addon is trying to use. Specifically this code (from `login()`):
```
params = {
            'client': self.client,
            'legacy': 'true'
}
```
To be honest this is just speculation on my part, but if this turns out to be the case I'm not sure how to solve it as I'd be surprised if there wasn't a good reason `legacy` was set to `true` in the first place.

It would be great if @emilsvennesson could chime in, but I know he has previously indicated that he has little interest in maintaining this addon anymore, which may not bode well for getting this issue solved. At least in the short term. I'm definitely willing to at least try to update the addon, but to be honest I have no idea of where to start when it comes to figuring out the API changes that then translate into code changes.

**Comment by emilsvennesson** [comment]
Hello friends!

I am surprised that the add-on kept on working to this point considering nothing has been done in a year... I'm sorry for abandoning it, but I simply have had other things that's been taking up my spare time.

It looks, just from a brief look at the log file supplied, like (as @kjerstadius said) that they've switched up their login API. If that's the only thing they've changed, then it shouldn't be that difficult to get it back up and running again. Unfortunately, I don't even have an account right now so I can't look into if it's something that can be fixed quickly.

**Comment by kjerstadius** [comment]
No worries, life happens and priorities change.

I have a CMore account and an interest in this addon. If you could give me some pointers on how to try to figure out the API changes that would be awesome. Like, how did you figure out the API in the first place? Granted, I didn't look that hard, but it doesn't seem like it's publicly documented. Anyway, if I can get things back in working order I'll happily submit a pull request and perhaps then we can discuss a more long term plan for this addon?

**Comment by emilsvennesson** [comment]
I'm happy that you're interested in continuing maintaining the add-on! :-) There is quite a lot that could be done to get this add-on back in a decent state. Python 3 support is for instance much needed; without that we're not even allowed to submit new releases to the official repository.

I just used mitmproxy on the website/mobile app to figure out how the official apps behaved. Some of the API:s actually have public documentation as well (such as the search API: https://cmore-search.b17g.services/docs/). I don't think you're going to find any public documentation on the login API though...

The add-on is a hack job between the website and the mobile apps, and I never really got around to finish the rewrite I started at https://github.com/emilsvennesson/kodi-cmore/commit/25c136f44f6232238c2944b4b67056d1a2a9d908 - that's why some of the listings are incomplete (https://github.com/emilsvennesson/kodi-cmore/issues/29) and why items are shown in a weird random order.

**Comment by macardi** [comment]
Sadly I can be of no help, exept with testing of course. I use this addon on a daily basis, so it would be great if it could be fixed.

**Comment by meeshen** [comment]
I just want to chime in that I noticed the same problem as well, and digging around led me to think it was the login API. I tried some quick fixes (like changing the shape of some objects to adhere to errors) but I am not experienced enough to get it working, sadly. On the plus side, my SO was watching Love Island with it, which I now, luckily, don't have to see anymore. ;)

**Comment by subheeroo** [comment]
C More introduced user profiles, similar to how Netflix and other services provide different user profiles for the entire family under one account, the same day the add-on stopped working. I believe this is what's causing the add-on to fail. There's simply an extra step now on each login where you have to choose a user profile. Perhaps this is somewhat easy to fix? Unfortunately I have no idea how add-ons work I'm just trying to provide a little detail to what may be the issue. 

I'm sad to hear you have stopped working on the add-on @emilsvennesson but I understand your decision. If you still want to revive it though, I know C More allows 2 weeks free for new accounts.

**Comment by Leatherface75** [comment]
@jsageryd maybe is able to give needed information about this.

If it's only the problem with choosing profile it should be an easy fix.

**Comment by kjerstadius** [comment]
Slight update: I have been able to figure out how to login. It seems to require a query now, similar to how `get_channels()` is already working. With some code changes I'm now able to login, but unable to start streams as I get a `401 - SESSION_NOT_AUTHENTICATED` error upon trying to start a stream. At least browsing seems to work fine still. I'll continue trying to figure this out, but I only have limited time so I can't really say when I (hopefully) find a solution.

**Comment by macardi** [comment]
Thanks for the update! Glad to hear that you working on finding a solution. Really appreciate it.

**Comment by kjerstadius** [comment]
As it turned out, figuring out the `get_stream()` authentication problem maybe wasn't so difficult after all. I've been able to get the plugin running again in my environment and I successfully used it for a few hours this evening. I still consider my updates experimental, but for those of you who'd like to try, have a look a the `login-api-update` branch of [my fork](https://github.com/kjerstadius/kodi-cmore/tree/login-api-update). Basically, it updates a few methods in `cmore.py` with the largest changes obviously being to the `login()` method.

If you're still unable to login using the code from my branch, reset the plugin to default settings (there's an option for it on the right hand side of the settings panel). I lost my "old" credentials file in debugging the plugin early on, so I'm unsure whether the new contents/format potentially overlaps with anything in the old dictionary, which could lead to the updated conditionals being defeated inadvertently.

Anyway, give it a go if you want and report back :)

**Comment by emilsvennesson** [comment]
@kjerstadius Nice job! I actually did some work on this as well, but I won't be able to test everything properly. Do you know if the operator login stuff is even needed anymore? Also, I threw out all the credentials code and just saved the token directly in settings.xml.

**Comment by kjerstadius** [comment]
@emilsvennesson Thanks! I have no idea about the operator stuff as I've never used it and don't really know what the use case was/is. In general I just tried to keep things as similar as possible to before, just with the updated login. Cleanup and refactoring might make sense, but can come later IMO. To be honest, I'm still wrapping my head around how the plugin works, so making too large changes comes with the risk of breaking things horribly due to a misunderstanding (on my part) of how things work.

Edit: What was the use case for operator?

**Comment by emilsvennesson** [comment]
@kjerstadius It is/was possible to login with your TV providers credentials, so there was a lot of additional code needed to get that working. I have no idea if they've changed that and unified the API, otherwise that's very likely to still be broken now. 

I pushed a commit with the changes I did, but it needs testing. I noticed that you hardcoded some sha256 hashes in your fork; I think those are personal (?). I have no idea how they're being generated at least, so I think it's wise to avoid sending that information unless it's required.

**Comment by kjerstadius** [comment]
Hmm, you may be right about the hashes. I got it into my head that they somehow represented the operations themselves (i.e. the query type or something similar), but not now that I look at it again I'm not so sure. I'll remove that code for now and see what happens.

**Comment by Leatherface75** [comment]
API for Operators still work but both email and operator login fails for me when trying to start a stream. Browsing works fine except for channels.
Gonna test on another machine and see if it's same there hmms.

**Comment by jsageryd** [comment]
Hi. I'm a dev at TV4 / C More. We recently killed off our old account/login service, so that's probably the reason this isn't working anymore. `account-delta` is the correct one to use, as @kjerstadius also mentions.

As for operator login, the typical flow would be that the user activates their account once to be able to login using regular C More credentials.

We also very recently launched profiles for C More, but this is not related. Any client without support for profiles should work as expected just as before, but is then locked to one profile.

I should also mention that while we don't unnecessarily try to hide our APIs, we also don't officially support third-party clients like this one (things might break at any time, sorry).

**Comment by macardi** [comment]
I can confirm that its working again after the last commits. Really good work, big thanks.

**Comment by Leatherface75** [comment]
How are you guys getting this to work?
I have tried on 2 computers now and stream fails when starting.
I have tried remove all settings and tried with both login methods and both fails.
I also tried remove widewine and install it again and still the same.
Login and browsing works fine so doesn't seem to be that.

**Comment by Leatherface75** [comment]
Hmm even Google Chrome fails says i am behind VPN or Proxy when i am not.
Removing cookies etc doesn't help either.

**Comment by emilsvennesson** [comment]
@jsageryd Thanks a lot for the answers (as always)! It's much appreciated. Okay, so that means we could probably kill off the old operator login code if you now have to tie it to a normal C More account. That makes everything so much easier.

I do have one more question if you don't mind: do you know what the sha 256 hash is when requesting data from the GraphQL API? It's getting sent with every query, but I'm not sure whether it's needed or how it's getting generated.
```
{"persistedQuery"{"version":1,"sha256Hash":"3e0c2382328ca28358e471728781c95a954b5061385d6ebd9295563bee58842f"}}
```
@Leatherface75 Well, we wouldn't know without a debug log... :-)

**Comment by Leatherface75** [comment]
Gonna fix a log soon but something is strange when even Google Chrome fails and says i am behind VPN or Proxy. I have VPN for servers etc but i am not connecting with it right now.
EDIT: Now i see the problem it doesn't accept my IPv6 address. This causes big problems for me because i use that for my network.
@jsageryd Is it possible to whitelist my own IP addresses i use? It's personal ones that noone else use.

**Comment by Leatherface75** [comment]
Seems i got it working with some manual added hostnames in hosts file but channels not working and many programs and movies is not working. Programs that is free on TV4 Play seems to work.

**Comment by emilsvennesson** [comment]
@Leatherface75 That error is related to script.module.inputstreamhelper. Download the latest version of inputstreamhelper at https://github.com/emilsvennesson/script.module.inputstreamhelper/releases and try again. If that doesn't work, then open an issue on that GitHub page instead.

**Comment by Leatherface75** [comment]
I will try but i have had that inputstream error for long time as i can remember and i have no problems with other addons using widevine etc. This addon also worked fine until this change with login.

**Comment by Leatherface75** [comment]
Seems i got it working on 1 machine now atleast but still strange that other addons depending on widevine worked. But on the other machine i have same problem with same version as above really strange.
Another problem it doesn't show any channels again.
Maybe it's that old problem that it didn't show after midnight?
I did some change earlier in old version but i don't remember what i changed.

**Comment by wagnerius** [comment]
> I do have one more question if you don't mind: do you know what the sha 256 hash is when requesting data from the GraphQL API? It's getting sent with every query, but I'm not sure whether it's needed or how it's getting generated.
> 
> ```
> {"persistedQuery"{"version":1,"sha256Hash":"3e0c2382328ca28358e471728781c95a954b5061385d6ebd9295563bee58842f"}}

@emilsvennesson The hash is generated by the clients in order to use persisted queries https://www.apollographql.com/docs/apollo-server/performance/apq/#using-get-requests-with-apq-on-a-cdn

**Comment by psonnosp** [comment]
I don't know if there's some hidden setting somewhere on CMORE.se that let you create a login that's connected to your operator login but that's still the only possible way for me to login.

**Comment by jsageryd** [comment]
> I don't know if there's some hidden setting somewhere on CMORE.se that let you create a login that's connected to your operator login but that's still the only possible way for me to login.

Whether or not this is possible depends on what operator you have.

**Comment by psonnosp** [comment]
> > I don't know if there's some hidden setting somewhere on CMORE.se that let you create a login that's connected to your operator login but that's still the only possible way for me to login.
> 
> Whether or not this is possible depends on what operator you have.

OK. You made it sound like everyone could do it and @emilsvennesson then talked about removing that login option. So please don't do that, I kind of sure I'm not the only one having access via Telia so that would probably ruin this plugin for a lot of people.

**Comment by Leatherface75** [comment]
Hmm i haven't tested after latest changes but on webbrowser i can use both email login and operator login. But you need to connect your login to your operator login first.

**Comment by emilsvennesson** [comment]
So I spent some time on this today and both C More logins and operator logins should work now, which means that I'm going to close this issue. Please open a new issue if you find any bugs with the new code!
